### ISSUE TITLE
Mixin warnings in *debug.log*: `@ModifyConstant conflict` and `@Final`. What they means?

### ISSUE THREAD

**Issue by Krutoy242** [ACGaming/UniversalTweaks#15]
I have various warnings about mixins after installing UniversalTweaks.

Is everything ok? Or i forgot to remove some incompatible mods?

```less
[Client thread/WARN] [mixin]: @ModifyConstant conflict. Skipping mixins.plustweaks.json:MixinBlockCactus->@ModifyConstant::modifyConstant_BlockCactus(I)I with priority 1000, already redirected by mixins.tweaks.plantables.json:UTCactusSizeMixin->@ModifyConstant::utCactusSize(I)I with priority 1000
[Client thread/WARN] [mixin]: @ModifyConstant conflict. Skipping mixins.plustweaks.json:MixinBlockReed->@ModifyConstant::modifyConstant_BlockReed(I)I with priority 1000, already redirected by mixins.tweaks.plantables.json:UTSugarCaneSizeMixin->@ModifyConstant::utSugarCaneSize(I)I with priority 1000
[Client thread/WARN] [mixin]: @Final field field_147697_e:Lnet/minecraft/client/audio/SoundRegistry; in mixins.tweaks.audioreload.json:UTAudioReloadMixin should be final
[Client thread/WARN] [mixin]: @Final field field_147698_b:Lorg/apache/logging/log4j/Logger; in mixins.tweaks.audioreload.json:UTAudioReloadMixin should be final
```

[debug.log](https://github.com/ACGaming/UniversalTweaks/files/10148118/debug.log)

**Comment by ACGaming** [comment]
Thanks for the report!
Conflicting mixins have been fixed in
https://github.com/ACGaming/UniversalTweaks/commit/8f75ca5fdbe3e1c50a6fc8c45c40a78cb3dfc729
and final fields have been fixed in
https://github.com/ACGaming/UniversalTweaks/commit/a4211b3612c73f55c3c09a6e14eb5eef3f690191
You can grab the latest build [here](https://github.com/ACGaming/UniversalTweaks/suites/9654840165/artifacts/461860779) or wait for the next release! 🙂
