### ISSUE TITLE
What means `WARN: @Mixin AmbientOcclusionFace is public in UTSmoothLightingMixin and should be specified`?

### ISSUE THREAD

**Issue by Krutoy242** [ACGaming/UniversalTweaks#181]
After one of recently UT updates, i found new WARN line in my debug.log file:

```less
[main/WARN] [mixin]: @Mixin target net/minecraft/client/renderer/BlockModelRenderer$AmbientOcclusionFace is public in mixins.bugfixes.misc.smoothlighting.json:UTSmoothLightingMixin and should be specified in value
```

What this warnings means? Does this means `B:"Accurate Smooth Lighting"=true` option not working at all?

[debug.log](https://github.com/ACGaming/UniversalTweaks/files/11451799/debug.log)

**Comment by ACGaming** [comment]
This tweak injects into AmbientOcclusionFace, which is private subclass of BlockModelRenderer. Because you can‘t reference private subclass targets directly, you have to do so via a string.
In your scenario, CreativeCore changes the visibility of the subclass to public for its own purposes and Mixin prints this warning.
Short answer: Modpack-specific warning, nothing to worry about, works.
