### ISSUE TITLE
debug.log ERROR: `Critical problem: mixins:UTRealmsButtonMainMenuMixin from mod UniversalTweaks target GuiMainMenu was loaded too early.`

### ISSUE THREAD

**Issue by Krutoy242** [ACGaming/UniversalTweaks#232]
After recent updates, i started to receive this error in log file:

```less
[main/ERROR] [mixin]: Critical problem: mixins.tweaks.misc.buttons.realms.json:UTRealmsButtonMainMenuMixin from mod UniversalTweaks_1_12_2_1_7_0 target net.minecraft.client.gui.GuiMainMenu was loaded too early.
```

What does this means? Can it be related to `CustomMainMenu` mod?

[debug.log](https://github.com/ACGaming/UniversalTweaks/files/12038096/debug.log)

**Comment by ACGaming** [comment]
Possibly, going to look into it eventually. Is the tweak still working?

**Comment by Krutoy242** [comment]
>  Is the tweak still working?
I dont know! How to check? I dont know what is "Realms" button

**Comment by ACGaming** [comment]
It‘s to hide the „Minecraft Realms“ button from the main menu, which is leading to MOJANG‘s official servers (which are not available for Minecraft 1.12 anymore). But when you‘re using Custom Main Menu, you‘re customizing the main menu either way and can‘t directly witness the effects of the tweak.

**Comment by jchung01** [comment]
As mentioned, CustomMainMenu does hide the effects of the tweak, but this error is probably due to RandomPatches for the same reason as Red-Studio-Ragnarok/Valkyrie#10, just that UT doesn't cause a crash compared to Valkyrie. Testing with just UT and RandomPatches shows that the tweak indeed does not work because RandomPatches [performs ASM transformation](https://github.com/TheRandomLabs/RandomPatches/blob/1.12/src/main/java/com/therandomlabs/randompatches/patch/client/GuiIngameMenuPatch.java) on GuiMainMenu.

**Comment by ACGaming** [comment]
Interesting that these issues are related, thanks for the insight! Guess it‘s time to devour RandomPatches for good! 😏
