### ISSUE TITLE
[Compatibility] Auto Jump step assist replacement makes Void Thaumaturge Boots own step assist not work

### ISSUE THREAD

**Issue by Vapaman** [ACGaming/UniversalTweaks#523]
Having Auto Jump Replacement true messes up the step assist on Thaumic Augmentations Void Thaumaturge boots. This does not happen with the regular Boots of The Traveller.

To others having this issue: circumvent the issue by putting Auto Jump Step assist as false in the Tweaks.cfg

Tested with these mods Installed:
Thaumic Augmentation 2.1.13 + Depencies (Baubles and Thaumcraft)
UniversalTweaks 1.12.0 + Depencies (MixinBooter 9.1, ConfigAnytime 3.0)

**Comment by jchung01** [comment]
This is specifically when the `Auto Jump Replacement` tweak is on AND Auto-Jump is off in the controls. Should be fixed by the PR.

There is still a bug that allows you to step up more than 1.25 blocks in a certain scenario due to the order in which the Void Thaumaturge boots and UT's tweak to step height is applied, but you can enable the `MovementCompat` option in `thaumicaugmentation.cfg` to fix it.
