### ISSUE TITLE
Block Overlay fix incompatible with Portal Gun

### ISSUE THREAD

**Issue by xJon** [ACGaming/UniversalTweaks#549]
With `Block Overlay Toggle` enabled, the portal view will be distorted from certain distances / angles:
![image](https://github.com/user-attachments/assets/93da67f6-77aa-4788-9f1d-6d44ca520915)

Also, despite being marked as requiring a Minecraft restart to take effect, disabling it via the configuration GUI resolves the issue within the same session.

**Comment by jchung01** [comment]
> Can confirm that using the latest Actions build does not resolve this. I assume adding the portal to the default blacklist could work, but portalgun:portal is not the correct value.

The correct id is `portalgun:block_portal`, but it turns out that doesn't work anyways. 
Explanation: Portal Gun is moving the player's position relative to a portal to render the preview in the other portal, which means sometimes the player's camera is technically in a block, which results in what you see there. Basically, the portal preview has to re-render the world in different perspectives, which happened to trigger the block overlay rendering. Should be fixed by the PR.

> Also, despite being marked as requiring a Minecraft restart to take effect, disabling it via the configuration GUI resolves the issue within the same session.

Yeah, many of the config options are marked as requiring an MC restart because setting a config from false -> true requires a restart for the mixins to apply, but not true -> false, which is what you were experiencing. There isn't really a way to express that in a config option, so to be safe any change to the config value warns you to restart.
